- Project.swift
- Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
- Resources/Assets.xcassets/Contents.json
#11 Assets 추가 및 Tuist 변경
- Assets 파일을 추가했습니다.
- Tuist 설정을 변경하였습니다. (Synthesized Resource Interface Accessors)
> ✨Assets 파일 추가 및 Tuist 설정 변경

- Project.swift
- Tuist/Dependencies.swift
#19 Lottie 추가
- Lottie dependency를 추가하였습니다. (version : 3.5.0)
[Lottie GitHub](https://github.com/airbnb/lottie-ios)
> ➕Lottie dependency 추가

- Sources/Presenter/Home/AddCourse/AddCourseMap/AddCourseMapViewController.swift
#69 
- AddCourseMapViewController에 버튼 클릭 시 실행할 메소드 추가
> 🚑NavigationBar Configure 에러 해결

- Sources/Presenter/Search/Course/Components/SearchTextField.swift
- Sources/Presenter/Search/SearchViewController.swift
> 📸키보드 Done 버튼 넣기

- Sources/App/AppCoordinator.swift
- Sources/Data/Course.swift
- Sources/Data/CourseImage.swift
- Sources/Data/Planet.swift
- Sources/Data/Tag.swift
- Sources/Data/User.swift
- Sources/Presenter/Home/HomeDTO/InquiryMyPlanetDTO.swift
- Sources/Presenter/Home/MyHome/HomeAPIService.swift
- Sources/Presenter/Home/MyHome/View/HomeDetailView.swift
- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
- SupportingFiles/MatStar-Info.plist
#83 
- 홈뷰에 내정보조회 api연결햇습니다
- api연결하는걸 잘 못해서 api하나씩 연결하겠습니다
> ✨내정보조회 api연결 

- Sources/Presenter/Home/AddCourse/RegisterCourse/Cell/ImageCollectionViewCell.swift
- Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
- Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
- Sources/Utility/Extensions/UIImagePickerController+.swift
- SupportingFiles/MatStar-Info.plist
#93 사진 추가, 삭제 기능 구현
- `Info.plist`에 사진 접근 권한 추가
- `UIImagePickerController` extension 추가
- 사진 추가, 삭제 기능 구현
<p>
</p>
- 사진 edit 시 crop rectangle이 정방형입니다. (직사각형으로 수정 어떻게 하는지 아직 모르겠어요)
> ✨[코스 등록] 사진 추가, 삭제 기능 구현

- .swiftlint.yml
- Sources/Data/AddCourse/AddCourseDTO.swift
- Sources/Data/AddCourse/AddCourseError.swift
- Sources/Data/AddCourse/AddCourseRepositoryImpl.swift
- Sources/Data/AddCourse/AddCourseResponse.swift
- Sources/Domain/AddCourse/AddCourseUseCase.swift
- Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewController.swift
- Sources/Presenter/Home/AddCourse/AddCourseComplete/AddCourseCompleteViewModel.swift
- Sources/Presenter/Home/AddCourse/AddCourseCoordinator.swift
- Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewController.swift
- Sources/Presenter/Home/AddCourse/RegisterCourse/RegisterCourseViewModel.swift
#98 코스등록 API 호출
- SwiftLint rule 변경
- 코스등록 API 호출 (token, planetId는 임시로 지정해두었습니다.)
> ✨코스 등록 API 호출

- Sources/Presenter/Profile/Profile/ProfileViewController.swift
#130 
- ProfileViewController에서 backgroundView를 삭제합니다.
> 🚑[HotFix] ProfileView backgroundView 삭제

- Sources/Presenter/LogMap/LogMapViewModel.swift
#138 
- Mock data에 `memo` 프로퍼티가 없어서 일어나는 빌드 에러를 해결합니다.
> 🚑Mock data memo 추가

- ComeIt.entitlements
- SupportingFiles/ComeIt-Info.plist
#145 프로젝트에 APNs를 활성화합니다.
- Background Modes의 Background fetch, Remote notifications를 활성화합니다.
- Push Notifications를 활성화합니다.
[[Apple] Apple push notification service (APNs) 설정하기](https://spiralmoon.tistory.com/entry/Apple-Apple-push-notification-service-APNs-설정하기)
[애플 개발자 certificate 25294에러](https://velog.io/@borijuyeong/애플-개발자-certificate-25294에러)
> ✨Background Mode, Push Notification 설정

- Sources/Domain/Entity/CourseEntity.swift
- Sources/Domain/Entity/PlaceEntity.swift
- Sources/Domain/Entity/PlanetEntity.swift
- Sources/Domain/Entity/ReviewEntity.swift
- Sources/Domain/Entity/UserEntity.swift
> ✨Entity 추가

- Sources/Domain/Entity/PlanetEntity.swift
> 🚑Entity 수정

- Sources/Data/Log/FetchConstellation/FetchConstellationDTO.swift
- Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
- Sources/Data/Log/FetchReview/FetchReviewDTO.swift
- Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
- Sources/Domain/Entity/ReviewEntity.swift
- Sources/Domain/Log/FetchReview/FetchReviewRepository.swift
- Sources/Domain/Log/FetchReview/FetchReviewUseCase.swift
+ #170 
- FetchReviewDTO.swift
- FetchReviewRepositoryImpl.swift
- FetchReviewRepository.swift
- FetchReviewUseCase.swift
> 4개의 작업을 완료했습니다.
> 클린 아키텍처를 참고했습니다.
> 질문하고 싶은 것이 있습니다.
```swift
private func convertToReviewEntity(_ responseData: FetchReviewDTO) -> [ReviewEntity] {
var reviews = [ReviewEntity]()
let emptyReview = ReviewEntity(name: "", imagesURL: [], content: "")
if let myReview = responseData.myReview {
let myReviewEntity = ReviewEntity(
name: myReview.writerName,
imagesURL: myReview.images,
content: myReview.content
)
reviews.append(myReviewEntity)
} else {
reviews.append(emptyReview)
}
if let mateReview = responseData.mateReview {
let mateReviewEntity = ReviewEntity(
name: mateReview.writerName,
imagesURL: mateReview.images,
content: mateReview.content
) …
```
> ✨ Log탭에서 코스의 리뷰를 불러오는 API연동

- Sources/App/AppDelegate.swift
- Sources/Presenter/Home/HomeDTO/SelectedDateCourseDTO.swift
- Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
#176 
- 승창이가 만들어준 flow에 분기처리해서 데이터 전달해놨습니다
- DTO가 변경되어서(코스조회에서 adress랑 카테고리 추가) 변경해놨습니다
> :sparkles: 화면전환 데이터 전달

- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
핫픽스입니다
- 작업 내용 및 변경사항
<p>
</p>
| 제목 | 제목 |
|-----|-----|
| <img src="" width="250"> | <img src="" width="250"> |
[]()
> :bug: selectedDateviewModel로 옮김

- Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
- Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
- Sources/Domain/Course/EditCourseUseCase.swift
- Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewModel.swift
#191 코스 계획, 계획한 코스 수정 API를 연결합니다.
- 후기 사진 compression 0.7로 수정
- 코스 계획 API 연결
- 계획된 코스 수정 API 연결
> ✨코스 계획, 계획한 코스 수정 API 연결

- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
#200 
- 홈화면 ui가 깨지는 상황이발생해서 수정했습니다
- 행성나가기, 탈퇴하기 버튼을 누르면 알람창이뜨고 확인을 누르면 탈퇴및 나가기 후 앱이 종료됩니다
https://user-images.githubusercontent.com/99013115/203012652-a7076f9d-6343-4fe3-97eb-905d7f450a57.mov
[리젝안먹게 앱종료시키는방법](https://zeddios.tistory.com/1252)
> ✨앱종료 기능 추가

- Sources/Data/PlaceSearch/PlaceSearchRepositoryImpl.swift
- Sources/Presenter/Home/Course/View/CourseMap/CourseMapViewController.swift
#193 
- PlaceListView를 내리지 않습니다.
- 장소 검색 지역을 한정하지 않습니다.
- 지도가 처음 보여질 때 나침반 기능을 끕니다.
- 장소 추가를 했을 때 지도에서 추가한 지역을 보여줍니다.
> ♻️코스 등록 UT 반영

- Sources/Core/APIManager.swift
- Sources/Data/Alarm/AlarmAPI.swift
- Sources/Data/Alarm/AlarmIdAPI.swift
- Sources/Data/Course/AddCourse/AddCourseRepositoryImpl.swift
- Sources/Data/Course/DeleteCourse/DeleteCourseRepositoryImpl.swift
- Sources/Data/Course/EditCourse/EditCourseRepositoryImpl.swift
- Sources/Data/Log/FetchConstellation/FetchConstellationRepositoryImpl.swift
- Sources/Data/Log/FetchReview/FetchReviewRepositoryImpl.swift
- Sources/Data/Review/AddReview/AddReviewRepositoryImpl.swift
- Sources/Data/Review/DeleteReview/DeleteReviewRepositoryImpl.swift
- Sources/Data/Review/EditReview/EditReviewRepositoryImpl.swift
- Sources/Presenter/Home/MyHome/HomeAPIService.swift
- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- Sources/Presenter/Home/MyHome/Views/PathTableFooter.swift
- Sources/Presenter/Home/MyHome/Views/PathTableViewCell.swift
- Sources/Presenter/Profile/Logout/UserWarning/ExitAPIService.swift
- Sources/Utility/Extensions/Double+.swift
#205 
```swift
final class APIManager {
#if DEBUG
static let baseURL = "https://comeit.site"
#else
static let baseURL = "https://wouldulike.site"
#endif
}
```
원래 "https://comeit.site"로 선언해놓은 부분들을 
```swift
APIManager.baseUR
```
로 바꿔놨습니다
앱이 실행되지 않는 문제가 있었는데
```swift
extension AlarmAPI {
private func addStringParameter(type: AlarmApiType, id: Int? = nil) -> String {
var urlString = host
switch type {
case .fetch:
urlString += "/notifications"
case .check:
guard let id = id else { return "" }
urlString += "/notifications/\(id)"
case .deleteAll:
urlString += "/notifications"
case .togglePermission:
urlString += "/users/notification"
case .deleteOne:
guard let id = id else { return "" }
urlString += "/notifications/\(id)"
}
return urlString
}
private func encodeUrl(string: String) -> String { …
```
> ♻️ 서버url분기처리

- Sources/Presenter/Home/HomeCoordinator.swift
- Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
- Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
#201 
- 알림을 누르거나 푸쉬를 누르면 로그탭 간 다음에 코스 리뷰 띄웁니다.
<p>
</p>
[]()
> 알림눌렀을때 로그탭간다음 코스 리뷰 띄우기

- Sources/Presenter/Log/MyConstellation/Cell/MyConstellationCollectionViewCell.swift
- Sources/Utility/Class/StarMaker.swift
> 🍀  myConstellation 수정

- Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
- Sources/Presenter/Profile/Profile/View/EditDateView.swift
- RegisterReviewView 기기대응
- EditDateView 기기대응
> ♻️UI 기기 대응

- Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
LogTicketView out of index Error 수정
> 🍀  로그 티켓 인덱스 오류 수정

- Sources/Presenter/Home/HomeDTO/UserInfoDTO.swift
- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
#222 
- 알림이 오면(알림이온다는 뜻은 읽지않은 알림이 있다는뜻입니다) 그때마다 viewwillappear를 호출하고 user안에잇는 hasnoticication의 bool값에 따라서 알림버튼의 이미지를 바꿔주는 작업을 했습니다
> :sparkles: 알림버튼 분기처리

- Sources/Presenter/Home/HomeCoordinator.swift
- Sources/Presenter/Log/LogCoordinator.swift
- Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
- Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
- Sources/Presenter/Log/LogMap/ViewController/LogMapViewController.swift
- Sources/Presenter/Log/LogMap/ViewModel/LogMapViewModel.swift
- Sources/Presenter/Log/LogTicket/View/LogTicketEmptyView.swift
- Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
- Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
- Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
- Sources/Presenter/Profile/ProfileCoordinator.swift
+ LogTicket Refactor 및 Log Map 수정
- 로그 티켓 뷰 색상 분기처리
- Coordinator 작업 (hideBottomBar)
- LogViewModel 쓸모없는 코드 삭제 및 파라미터 수정
> 🐛 LogTicket Refactor 및 Log Map 수정

- Sources/Presenter/Home/HomeDTO/UserInfoDTO.swift
- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
- 최신 dday라벨 빈배열로(배포 후 다음 버전에서 기능 추가)
- userInfoDTO에서 email optional처리(소셜로그인을하면 email이 없을 수 있기 때문에)
> 🚨homeview에서 최신 dday라벨 배포 준비, DTO optional수정

- Sources/Data/Log/FetchCourseLike/TapCourseLikeRepositoryImpl.swift
- Sources/Presenter/Alarm/AlarmViewController.swift
- Sources/Presenter/Log/LogHome/ViewController/LogHomeViewController.swift
- Sources/Presenter/Log/MyConstellation/ViewController/MyConstellationViewController.swift
> 🐛 로그 홈에서 현재 별자리 버튼이 안보이는 오류 수정 

- Sources/Core/APIManager.swift
- Sources/Presenter/Intro/Network/Base/TargetType.swift
핫픽스입니다
- 포딩의 요청으로 서버 url에서 www제거했습니다
> :bug: url 에서 www제거

- Sources/App/AppDelegate.swift
- Sources/Data/Alarm/AlarmIdAPI.swift
- Sources/Presenter/Log/LogHome/ViewModel/LogHomeViewModel.swift
파트너가 행성참여하면 푸시
푸시 클릭하면 홈뷰로 이동합니다.
>  행성 참여시 푸시후 홈뷰로 이동

- Sources/App/AppDelegate.swift
> foreground일때 안보이도록 push

- Sources/Presenter/Home/Course/View/RegisterReview/RegisterReviewViewController.swift
#238 
- 리뷰 작성 화면에서 deleteCourse API를 호출하는 조건을 추가하였습니다.
```swift
override func viewWillDisappear(_ animated: Bool) {
super.viewWillDisappear(animated)
self.removeNotifications()
if isMovingFromParent {
self.viewModel.deleteCourse()
}
}
```
> ♻️리뷰 작성 화면에서 deleteCourse API 호출 수정

- Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
`# + 이슈번호`로 관련 이슈를 알려주세요.
- 작업 내용 및 변경사항
<p>
</p>
| 제목 | 제목 |
|-----|-----|
| <img src="" width="250"> | <img src="" width="250"> |
[]()
> :bug: 행성나가기 view에서 backbutton tint color를 수정했습니다

- Sources/App/AppCoordinator.swift
- Sources/App/AppDelegate.swift
- Sources/Presenter/Alarm/AlarmViewModel.swift
> 푸쉬버그 및 나가기 수정

- Sources/App/AppDelegate.swift
- Sources/Presenter/Alarm/AlarmViewController.swift
- Sources/Presenter/Home/MyHome/ViewController/HomeViewController.swift
> 알람뷰에서 네비게이션탭바 없어지는 버그 수정

- Sources/Presenter/Log/LogCoordinator.swift
- Sources/Presenter/Log/LogImageFullScreen/Cell/FullScreenImageCollectionViewCell.swift
- Sources/Presenter/Log/LogImageFullScreen/ViewController/LogImageFullScreenViewController.swift
- Sources/Presenter/Log/LogImageFullScreen/ViewModel/LogImageFullScreenViewModel.swift
- Sources/Presenter/Log/LogTicket/Cell/LogImageCollectionViewCell.swift
- Sources/Presenter/Log/LogTicket/View/EmptyImageView.swift
- Sources/Presenter/Log/LogTicket/View/LogTicketView.swift
- Sources/Presenter/Log/LogTicket/ViewController/LogTicketViewController.swift
- Sources/Presenter/Log/LogTicket/ViewModel/LogTicketViewModel.swift
+ #233  
- 이미지가 없을 경우, 보여지는 뷰 분기 처리
- 이미지 클릭시, 확대 가능한 이미지 뷰어 추가
+ 클릭 이벤트 감지가 필요해, 기존 ScrollView -> CollectionView로 변경
[사진 뷰어앱을 만들어 보았다.](https://velog.io/@kirri1124/%EC%82%AC%EC%A7%84-%EB%B7%B0%EC%96%B4-%EC%95%B1%EC%9D%84-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B4%A4%EB%8B%A4)
> ✨ 이미지 없을 때, 처리 & 이미지 뷰어(이미지 확대 기능) 추가

- Sources/App/AppCoordinator.swift
- Sources/App/AppDelegate.swift
- Sources/Presenter/Intro/Scenes/FindPlanet/FindPlanetViewModel.swift
- Sources/Presenter/Profile/Logout/UserWarning/UserWarningViewController.swift
상대방이 행성 탈출 했을때
나(본인)이 푸쉬를 통하지 않고 앱을 클릭했을때
앱을 탈출하라는 뷰가 나오도록 구현.
> ♻️ 1차 QA수정사항 반영

- Sources/App/AppDelegate.swift
- Sources/Presenter/Alarm/AlarmViewModel.swift
- Sources/Presenter/Home/HomeCoordinator.swift
- Sources/Presenter/Home/MyHome/ViewModel/HomeViewModel.swift
`# + 이슈번호`로 관련 이슈를 알려주세요.
- 작업 내용 및 변경사항
<p>
</p>
| 제목 | 제목 |
|-----|-----|
| <img src="" width="250"> | <img src="" width="250"> |
[]()
> :recycle: youth 2차 qa반영
